export const PROVINCIAS_ARGENTINAS = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán',
] as const;

export type Provincia = typeof PROVINCIAS_ARGENTINAS[number];

export interface Ciudad {
  nombre: string;
  codigoPostal: string | null;
}

export const CIUDADES_POR_PROVINCIA: Record<Provincia, Ciudad[]> = {
  'Buenos Aires': [
    { nombre: 'La Plata', codigoPostal: '1900' },
    { nombre: 'Mar del Plata', codigoPostal: '7600' },
    { nombre: 'Bahía Blanca', codigoPostal: '8000' },
    { nombre: 'Quilmes', codigoPostal: '1878' },
    { nombre: 'Lanús', codigoPostal: '1824' },
    { nombre: 'Lomas de Zamora', codigoPostal: '1832' },
    { nombre: 'San Isidro', codigoPostal: '1642' },
    { nombre: 'Tigre', codigoPostal: '1648' },
    { nombre: 'Vicente López', codigoPostal: '1638' },
    { nombre: 'Avellaneda', codigoPostal: '1870' },
    { nombre: 'Banfield', codigoPostal: '1828' },
    { nombre: 'Berazategui', codigoPostal: '1884' },
    { nombre: 'Merlo', codigoPostal: '1722' },
    { nombre: 'Moreno', codigoPostal: '1744' },
    { nombre: 'Morón', codigoPostal: '1708' },
    { nombre: 'San Miguel', codigoPostal: '1663' },
    { nombre: 'Tres de Febrero', codigoPostal: '1676' },
    { nombre: 'Zárate', codigoPostal: '2800' },
    { nombre: 'Campana', codigoPostal: '2804' },
    { nombre: 'Escobar', codigoPostal: '1625' },
    { nombre: 'Pilar', codigoPostal: '1629' },
    { nombre: 'San Nicolás', codigoPostal: '2900' },
    { nombre: 'Junín', codigoPostal: '6000' },
    { nombre: 'Olavarría', codigoPostal: '7400' },
    { nombre: 'Tandil', codigoPostal: '7000' },
    { nombre: 'Necochea', codigoPostal: '7630' },
    { nombre: 'Azul', codigoPostal: '7300' },
    { nombre: 'Pergamino', codigoPostal: '2700' },
    { nombre: 'Chivilcoy', codigoPostal: '6620' },
    { nombre: 'Dolores', codigoPostal: '7100' },
  ],
  'Catamarca': [
    { nombre: 'San Fernando del Valle de Catamarca', codigoPostal: '4700' },
    { nombre: 'Valle Viejo', codigoPostal: '4707' },
    { nombre: 'Fray Mamerto Esquiú', codigoPostal: '4705' },
    { nombre: 'Ambato', codigoPostal: '4711' },
    { nombre: 'Pomán', codigoPostal: '5311' },
    { nombre: 'Belén', codigoPostal: '4750' },
    { nombre: 'Santa María', codigoPostal: '4139' },
    { nombre: 'Tinogasta', codigoPostal: '5340' },
    { nombre: 'Andalgalá', codigoPostal: '4740' },
    { nombre: 'Recreo', codigoPostal: '4231' },
  ],
  'Chaco': [
    { nombre: 'Resistencia', codigoPostal: '3500' },
    { nombre: 'Barranqueras', codigoPostal: '3503' },
    { nombre: 'Villa Ángela', codigoPostal: '3540' },
    { nombre: 'Presidencia Roque Sáenz Peña', codigoPostal: '3700' },
    { nombre: 'Charata', codigoPostal: '3730' },
    { nombre: 'General San Martín', codigoPostal: '3630' },
    { nombre: 'Machagai', codigoPostal: '3534' },
    { nombre: 'Quitilipi', codigoPostal: '3530' },
    { nombre: 'Las Breñas', codigoPostal: '3722' },
    { nombre: 'Villa Berthet', codigoPostal: '3705' },
  ],
  'Chubut': [
    { nombre: 'Rawson', codigoPostal: '9103' },
    { nombre: 'Comodoro Rivadavia', codigoPostal: '9000' },
    { nombre: 'Trelew', codigoPostal: '9100' },
    { nombre: 'Puerto Madryn', codigoPostal: '9120' },
    { nombre: 'Esquel', codigoPostal: '9200' },
    { nombre: 'Sarmiento', codigoPostal: '9020' },
    { nombre: 'Gaiman', codigoPostal: '9105' },
    { nombre: 'Rada Tilly', codigoPostal: '9007' },
    { nombre: '28 de Julio', codigoPostal: '9107' },
    { nombre: 'Dolavon', codigoPostal: '9101' },
  ],
  'Córdoba': [
    { nombre: 'Córdoba', codigoPostal: '5000' },
    { nombre: 'Villa María', codigoPostal: '5900' },
    { nombre: 'Río Cuarto', codigoPostal: '5800' },
    { nombre: 'Villa Carlos Paz', codigoPostal: '5152' },
    { nombre: 'San Francisco', codigoPostal: '2400' },
    { nombre: 'Villa Allende', codigoPostal: '5105' },
    { nombre: 'Jesús María', codigoPostal: '5220' },
    { nombre: 'Unquillo', codigoPostal: '5109' },
    { nombre: 'La Calera', codigoPostal: '5151' },
    { nombre: 'Río Tercero', codigoPostal: '5850' },
    { nombre: 'Marcos Juárez', codigoPostal: '2580' },
    { nombre: 'Arroyito', codigoPostal: '2434' },
    { nombre: 'Bell Ville', codigoPostal: '2550' },
    { nombre: 'Leones', codigoPostal: '2594' },
    { nombre: 'Monte Cristo', codigoPostal: '2421' },
  ],
  'Corrientes': [
    { nombre: 'Corrientes', codigoPostal: '3400' },
    { nombre: 'Goya', codigoPostal: '3450' },
    { nombre: 'Mercedes', codigoPostal: '3470' },
    { nombre: 'Bella Vista', codigoPostal: '3441' },
    { nombre: 'Paso de los Libres', codigoPostal: '3230' },
    { nombre: 'Curuzú Cuatiá', codigoPostal: '3460' },
    { nombre: 'Monte Caseros', codigoPostal: '3220' },
    { nombre: 'Esquina', codigoPostal: '3196' },
    { nombre: 'Santo Tomé', codigoPostal: '3340' },
    { nombre: 'Ituzaingó', codigoPostal: '3302' },
  ],
  'Entre Ríos': [
    { nombre: 'Paraná', codigoPostal: '3100' },
    { nombre: 'Concordia', codigoPostal: '3200' },
    { nombre: 'Gualeguaychú', codigoPostal: '2820' },
    { nombre: 'Concepción del Uruguay', codigoPostal: '3260' },
    { nombre: 'Gualeguay', codigoPostal: '2840' },
    { nombre: 'Villaguay', codigoPostal: '3240' },
    { nombre: 'Colón', codigoPostal: '3280' },
    { nombre: 'Federación', codigoPostal: '3206' },
    { nombre: 'Nogoyá', codigoPostal: '3150' },
    { nombre: 'Victoria', codigoPostal: '3153' },
  ],
  'Formosa': [
    { nombre: 'Formosa', codigoPostal: '3600' },
    { nombre: 'Clorinda', codigoPostal: '3610' },
    { nombre: 'Pirané', codigoPostal: '3606' },
    { nombre: 'El Colorado', codigoPostal: '3613' },
    { nombre: 'Las Lomitas', codigoPostal: '3630' },
    { nombre: 'Ibarreta', codigoPostal: '3624' },
    { nombre: 'Comandante Fontana', codigoPostal: '3620' },
    { nombre: 'Laguna Blanca', codigoPostal: '3615' },
    { nombre: 'Villa General Güemes', codigoPostal: '3612' },
    { nombre: 'Palo Santo', codigoPostal: '3608' },
  ],
  'Jujuy': [
    { nombre: 'San Salvador de Jujuy', codigoPostal: '4600' },
    { nombre: 'Palpalá', codigoPostal: '4612' },
    { nombre: 'Perico', codigoPostal: '4608' },
    { nombre: 'San Pedro de Jujuy', codigoPostal: '4500' },
    { nombre: 'Libertador General San Martín', codigoPostal: '4512' },
    { nombre: 'La Quiaca', codigoPostal: '4650' },
    { nombre: 'Humahuaca', codigoPostal: '4630' },
    { nombre: 'Tilcara', codigoPostal: '4624' },
    { nombre: 'El Carmen', codigoPostal: '4618' },
    { nombre: 'Monterrico', codigoPostal: '4614' },
  ],
  'La Pampa': [
    { nombre: 'Santa Rosa', codigoPostal: '6300' },
    { nombre: 'General Pico', codigoPostal: '6360' },
    { nombre: 'Toay', codigoPostal: '6303' },
    { nombre: 'Realicó', codigoPostal: '6200' },
    { nombre: 'General Acha', codigoPostal: '8200' },
    { nombre: 'Macachín', codigoPostal: '6307' },
    { nombre: 'Victorica', codigoPostal: '6212' },
    { nombre: 'Intendente Alvear', codigoPostal: '6221' },
    { nombre: 'Eduardo Castex', codigoPostal: '6380' },
    { nombre: 'Trenel', codigoPostal: '6369' },
  ],
  'La Rioja': [
    { nombre: 'La Rioja', codigoPostal: '5300' },
    { nombre: 'Arauco', codigoPostal: '5311' },
    { nombre: 'Chilecito', codigoPostal: '5360' },
    { nombre: 'Aimogasta', codigoPostal: '5313' },
    { nombre: 'Chamical', codigoPostal: '5380' },
    { nombre: 'Chepes', codigoPostal: '5470' },
    { nombre: 'Vinchina', codigoPostal: '5353' },
    { nombre: 'Famatina', codigoPostal: '5365' },
    { nombre: 'Nonogasta', codigoPostal: '5363' },
    { nombre: 'Villa Unión', codigoPostal: '5350' },
  ],
  'Mendoza': [
    { nombre: 'Mendoza', codigoPostal: '5500' },
    { nombre: 'San Rafael', codigoPostal: '5600' },
    { nombre: 'Godoy Cruz', codigoPostal: '5501' },
    { nombre: 'Luján de Cuyo', codigoPostal: '5507' },
    { nombre: 'Maipú', codigoPostal: '5515' },
    { nombre: 'Guaymallén', codigoPostal: '5521' },
    { nombre: 'Las Heras', codigoPostal: '5539' },
    { nombre: 'Rivadavia', codigoPostal: '5579' },
    { nombre: 'Tunuyán', codigoPostal: '5560' },
    { nombre: 'San Martín', codigoPostal: '5570' },
    { nombre: 'Malargüe', codigoPostal: '5613' },
    { nombre: 'General Alvear', codigoPostal: '5620' },
    { nombre: 'Santa Rosa', codigoPostal: '5596' },
    { nombre: 'La Paz', codigoPostal: '5594' },
  ],
  'Misiones': [
    { nombre: 'Posadas', codigoPostal: '3300' },
    { nombre: 'Eldorado', codigoPostal: '3380' },
    { nombre: 'Oberá', codigoPostal: '3360' },
    { nombre: 'Puerto Iguazú', codigoPostal: '3370' },
    { nombre: 'Apóstoles', codigoPostal: '3358' },
    { nombre: 'Leandro N. Alem', codigoPostal: '3315' },
    { nombre: 'San Vicente', codigoPostal: '3364' },
    { nombre: 'Jardín América', codigoPostal: '3328' },
    { nombre: 'Aristóbulo del Valle', codigoPostal: '3364' },
    { nombre: 'Montecarlo', codigoPostal: '3384' },
  ],
  'Neuquén': [
    { nombre: 'Neuquén', codigoPostal: '8300' },
    { nombre: 'Cutral Co', codigoPostal: '8318' },
    { nombre: 'Plottier', codigoPostal: '8316' },
    { nombre: 'Zapala', codigoPostal: '8340' },
    { nombre: 'San Martín de los Andes', codigoPostal: '8370' },
    { nombre: 'Villa La Angostura', codigoPostal: '8407' },
    { nombre: 'Centenario', codigoPostal: '8309' },
    { nombre: 'Rincón de los Sauces', codigoPostal: '8319' },
    { nombre: 'Chos Malal', codigoPostal: '8353' },
    { nombre: 'Aluminé', codigoPostal: '8345' },
  ],
  'Río Negro': [
    { nombre: 'Viedma', codigoPostal: '8500' },
    { nombre: 'San Carlos de Bariloche', codigoPostal: '8400' },
    { nombre: 'General Roca', codigoPostal: '8332' },
    { nombre: 'Cipolletti', codigoPostal: '8324' },
    { nombre: 'Allen', codigoPostal: '8328' },
    { nombre: 'Cinco Saltos', codigoPostal: '8303' },
    { nombre: 'Villa Regina', codigoPostal: '8336' },
    { nombre: 'El Bolsón', codigoPostal: '8430' },
    { nombre: 'Ingeniero Jacobacci', codigoPostal: '8418' },
    { nombre: 'Luis Beltrán', codigoPostal: '8334' },
  ],
  'Salta': [
    { nombre: 'Salta', codigoPostal: '4400' },
    { nombre: 'San Salvador de Jujuy', codigoPostal: '4600' },
    { nombre: 'Orán', codigoPostal: '4530' },
    { nombre: 'Tartagal', codigoPostal: '4560' },
    { nombre: 'Metán', codigoPostal: '4440' },
    { nombre: 'Rosario de la Frontera', codigoPostal: '4192' },
    { nombre: 'Cafayate', codigoPostal: '4427' },
    { nombre: 'Cerrillos', codigoPostal: '4403' },
    { nombre: 'La Caldera', codigoPostal: '4401' },
    { nombre: 'General Güemes', codigoPostal: '4430' },
  ],
  'San Juan': [
    { nombre: 'San Juan', codigoPostal: '5400' },
    { nombre: 'Rawson', codigoPostal: '5423' },
    { nombre: 'Rivadavia', codigoPostal: '5407' },
    { nombre: 'Santa Lucía', codigoPostal: '5419' },
    { nombre: 'Pocito', codigoPostal: '5417' },
    { nombre: 'Chimbas', codigoPostal: '5415' },
    { nombre: 'Albardón', codigoPostal: '5413' },
    { nombre: 'Caucete', codigoPostal: '5442' },
    { nombre: 'Jáchal', codigoPostal: '5460' },
    { nombre: 'Calingasta', codigoPostal: '5403' },
  ],
  'San Luis': [
    { nombre: 'San Luis', codigoPostal: '5700' },
    { nombre: 'Villa Mercedes', codigoPostal: '5730' },
    { nombre: 'Merlo', codigoPostal: '5881' },
    { nombre: 'La Toma', codigoPostal: '5750' },
    { nombre: 'Concarán', codigoPostal: '5770' },
    { nombre: 'Justo Daract', codigoPostal: '5738' },
    { nombre: 'Tilisarao', codigoPostal: '5773' },
    { nombre: 'Nueva Galia', codigoPostal: '6218' },
    { nombre: 'Buena Esperanza', codigoPostal: '5777' },
    { nombre: 'Quines', codigoPostal: '5711' },
  ],
  'Santa Cruz': [
    { nombre: 'Río Gallegos', codigoPostal: '9400' },
    { nombre: 'Caleta Olivia', codigoPostal: '9011' },
    { nombre: 'El Calafate', codigoPostal: '9405' },
    { nombre: 'Pico Truncado', codigoPostal: '9019' },
    { nombre: 'Las Heras', codigoPostal: '9017' },
    { nombre: 'Puerto Deseado', codigoPostal: '9050' },
    { nombre: 'Perito Moreno', codigoPostal: '9040' },
    { nombre: 'Puerto San Julián', codigoPostal: '9310' },
    { nombre: 'Comandante Luis Piedra Buena', codigoPostal: '9320' },
    { nombre: 'Gobernador Gregores', codigoPostal: '9311' },
  ],
  'Santa Fe': [
    { nombre: 'Santa Fe', codigoPostal: '3000' },
    { nombre: 'Rosario', codigoPostal: '2000' },
    { nombre: 'Rafaela', codigoPostal: '2300' },
    { nombre: 'Venado Tuerto', codigoPostal: '2600' },
    { nombre: 'Reconquista', codigoPostal: '3560' },
    { nombre: 'Santo Tomé', codigoPostal: '3016' },
    { nombre: 'Esperanza', codigoPostal: '3080' },
    { nombre: 'Villa Gobernador Gálvez', codigoPostal: '2124' },
    { nombre: 'San Lorenzo', codigoPostal: '2200' },
    { nombre: 'Casilda', codigoPostal: '2170' },
    { nombre: 'Gálvez', codigoPostal: '2252' },
    { nombre: 'Sunchales', codigoPostal: '2322' },
    { nombre: 'Firmat', codigoPostal: '2630' },
    { nombre: 'Arroyo Seco', codigoPostal: '2128' },
  ],
  'Santiago del Estero': [
    { nombre: 'Santiago del Estero', codigoPostal: '4200' },
    { nombre: 'La Banda', codigoPostal: '4300' },
    { nombre: 'Frías', codigoPostal: '4230' },
    { nombre: 'Añatuya', codigoPostal: '3760' },
    { nombre: 'Termas de Río Hondo', codigoPostal: '4220' },
    { nombre: 'Monte Quemado', codigoPostal: '3712' },
    { nombre: 'Quimilí', codigoPostal: '3740' },
    { nombre: 'Loreto', codigoPostal: '4238' },
    { nombre: 'Sumampa', codigoPostal: '4225' },
    { nombre: 'Villa Ojo de Agua', codigoPostal: '5250' },
  ],
  'Tierra del Fuego': [
    { nombre: 'Ushuaia', codigoPostal: '9410' },
    { nombre: 'Río Grande', codigoPostal: '9420' },
    { nombre: 'Tolhuin', codigoPostal: '9412' },
    { nombre: 'San Sebastián', codigoPostal: '9423' },
    { nombre: 'Puerto Almanza', codigoPostal: '9411' },
    { nombre: 'Lago Escondido', codigoPostal: '9413' },
    { nombre: 'Estancia Harberton', codigoPostal: '9410' },
    { nombre: 'Puerto Williams', codigoPostal: null },
    { nombre: 'Cabo de Hornos', codigoPostal: null },
    { nombre: 'Porvenir', codigoPostal: null },
  ],
  'Tucumán': [
    { nombre: 'San Miguel de Tucumán', codigoPostal: '4000' },
    { nombre: 'Yerba Buena', codigoPostal: '4107' },
    { nombre: 'Tafí Viejo', codigoPostal: '4103' },
    { nombre: 'Concepción', codigoPostal: '4146' },
    { nombre: 'Aguilares', codigoPostal: '4157' },
    { nombre: 'Famaillá', codigoPostal: '4132' },
    { nombre: 'Monteros', codigoPostal: '4142' },
    { nombre: 'Tafí del Valle', codigoPostal: '4137' },
    { nombre: 'Simoca', codigoPostal: '4172' },
    { nombre: 'Lules', codigoPostal: '4128' },
  ],
};

export const obtenerCiudades = (provincia: string): Ciudad[] => {
  if (provincia === 'Otra') {
    return [];
  }
  return CIUDADES_POR_PROVINCIA[provincia as Provincia] || [];
};

// Función auxiliar para obtener solo los nombres (compatibilidad hacia atrás)
export const obtenerNombresCiudades = (provincia: string): string[] => {
  return obtenerCiudades(provincia).map((ciudad) => ciudad.nombre);
};



